# -*- coding: utf-8 -*-
"""NUMPY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zz-i5nOESl4UalFviNp3Xam6tjzzU8CZ
"""

# NumPy Basics: Arrays and Vectorized Computation
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

"""# creating a list containing elements 
# belonging to different data types
sample_list = [1,"Yash",['a','e']]
print(sample_list)

# creating an array containing same 
# data type elements 
import array
sample_array = array.array('i', [1, 2, 3])  
# accessing elements of array
for i in sample_array:
     print(i)



"""

import numpy as np
my_arr = np.arange(10)
my_list = list(range(10))

print(my_arr)

print(my_list)

# Commented out IPython magic to ensure Python compatibility.
# %time for _ in range(10): my_arr2 = my_arr * 2

my_arr2